[build]
  base = "."
  publish = "./dist"
  command = "astro build"

# TODO: Enable this plugin (TEMPORARILY DISABLED)
# See: https://github.com/netlify-labs/netlify-plugin-a11y
# [[plugins]] 
#   package = "@netlify/plugin-a11y"
#   [plugins.inputs]
#     # Check all HTML files in this project
#     checkPaths = ['/']
#     # Fail the build if a11y issues are found
#     failWithIssues = true
#     # Perform a11y check against WCAG 2.1 AAA
#     wcagLevel = 'WCAG2AAA'

# See: https://github.com/cdeleeuwe/netlify-plugin-submit-sitemap#readme
[[plugins]]
  package = "netlify-plugin-submit-sitemap"
	[plugins.inputs]
	# The base url of your site (optional, default = main URL set in Netlify)
	baseUrl = "https://hammadmajid.me"
	# Path to the sitemap URL (optional, default = /sitemap.xml)
	sitemapPath = "/sitemap-index.xml"
	# Time in seconds to not submit the sitemap after successful submission
	ignorePeriod = 0
	# Enabled providers to submit sitemap to (optional, default = 'google', 'yandex'). Possible providers are currently only 'google', 'yandex'.
	providers = [
		"google",
		"yandex"
	]
